from abc import ABC, abstractmethod
from typing import Literal

from pydantic import BaseModel, Field

from agentic_learning_portal.api.progress import ProgressListener


class ProblemGenerationPromptInput(BaseModel, ABC):
    """Input parameters for problem generation prompt."""

    @abstractmethod
    def build_user_prompt(self) -> str:
        """Build the user prompt sent to the LLM."""

class GeneratedTask(BaseModel):
    """
    Task generated by the LLM model.
    """
    topic: str = Field(
        ...,
        description="The mathematical topic (e.g., 'Algebra', 'Calculus', 'Geometry')."
    )
    text: str = Field(
        ...,
        description="The actual text or question of the mathematical problem."
    )
    complexity: Literal['easy', 'medium', 'hard'] = Field(
        ...,
        description="The difficulty level of the problem."
    )
    correct_answer: str | int | float = Field(
        ...,
        description="The correct answer to the problem, which can be an integer, float, or string."
    )
    solution: str = Field(
        ...,
        description=(
            "Step-by-step explanation of how to arrive at the correct answer, "
            "clear enough for a student to follow. Write math in plain text, "
            "not LaTeX markup."
        ),
    )


class VerificationResult(BaseModel):
    """Outcome of an independent judge checking a generated task against ground truth."""

    judge: str = Field(
        ...,
        description="Name of the judge (e.g., 'wolframalpha').",
    )
    verified: bool = Field(
        ...,
        description="Whether the generated answer matches the judge's ground truth.",
    )
    expected_answer: str | int | float | None = Field(
        default=None,
        description="The answer the LLM produced (task.correct_answer).",
    )
    judge_answer: str | None = Field(
        default=None,
        description="The answer reported by the judge, as raw text.",
    )
    detail: str = Field(
        default="",
        description="Human-readable explanation of the match or mismatch.",
    )


class Judge(ABC):
    """Contract that every verification judge must satisfy.

    A judge inspects a generated ``task`` and returns its verdict. The task is
    accepted only when every judge in the ensemble verifies it. Both
    ``WolframAlphaJudge`` and ``QwenMathJudge`` implement this interface.
    """

    @abstractmethod
    async def verify(
        self,
        task: GeneratedTask,
        *,
        listener: ProgressListener | None = None,
    ) -> VerificationResult:
        """Return the judge's verdict on ``task``.

        ``listener`` is optional: when provided, the judge reports its progress
        steps (translation, computation, verdict) so callers can surface live
        generation progress. Ignore it if the judge has no discrete steps.
        """