from abc import ABC, abstractmethod
from typing import Literal

from pydantic import BaseModel, Field


class ProblemGenerationPromptInput(BaseModel, ABC):
    """Input parameters for problem generation prompt."""

    @abstractmethod
    def build_user_prompt(self) -> str:
        """Build the user prompt sent to the LLM."""

class GeneratedTask(BaseModel):
    """
    Task generated by the LLM model.
    """
    topic: str = Field(
        ...,
        description="The mathematical topic (e.g., 'Algebra', 'Calculus', 'Geometry')."
    )
    text: str = Field(
        ...,
        description="The actual text or question of the mathematical problem."
    )
    complexity: Literal['easy', 'medium', 'hard'] = Field(
        ...,
        description="The difficulty level of the problem."
    )
    correct_answer: str | int | float = Field(
        ...,
        description="The correct answer to the problem, which can be an integer, float, or string."
    )